---
- name: Deploy ECS Task and Service with EC2
  hosts: localhost
  gather_facts: False
  vars:
    aws_region: "us-east-1"
    ecs_cluster_name: "php-app-ecs"
    ecs_task_definition_name: "ansible-task-definition"
    ecs_service_name: "php-ecs-service"
    ecs_container_name: "ansible_php"
    ecs_container_image: "736116236436.dkr.ecr.us-east-1.amazonaws.com/ecs2-img:latest"
    ec2_instance_type: "t2.medium"  # Specify your desired instance type here
    ec2_key_name: "test-1"  # Your EC2 key pair name
    ec2_security_group: "sg-0a85d937517e6a7b1"  # Security group for EC2 instances
    subnet_ids:
      - "subnet-095be323bd97dc9a4"
      - "subnet-0c8e1eaaaff0a0726"
      - "subnet-0e3db30d9fdcb6414"
      - "subnet-04b85618616f2da9d"
      - "subnet-0925766f7ff391b44"
  tasks:
    - name: Ensure python3-pip is installed
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Ensure boto3 is installed
      become: yes
      apt:
        name: python3-boto3
        state: present

    - name: Ensure botocore is installed
      become: yes
      apt:
        name: python3-botocore
        state: present

    - name: Create ECS Cluster
      command: "aws ecs create-cluster --cluster-name {{ ecs_cluster_name }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"
      ignore_errors: yes  # Ignore errors if the cluster already exists

    - name: Launch EC2 instances for ECS Cluster
      ec2:
        key_name: "{{ ec2_key_name }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "ami-0de53d8956e8dcf80"  # Amazon Linux 2 AMI (replace with your desired AMI ID)
        wait: yes
        count: 1  # Number of instances to launch
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ subnet_ids | random }}"
        group_id: "{{ ec2_security_group }}"
        instance_tags:
          Name: "ECS Instance"
          Cluster: "{{ ecs_cluster_name }}"
      register: ec2

    - name: Add instances to ECS Cluster
      command: >
        aws ecs register-container-instance
